### ISSUE TITLE
Trouble understanding IMU Initialization

### ISSUE THREAD

**Issue by richaagrawal** [jingpang/LearnVIORB#20]
Thanks for integrating the IMU. I was going through your code and I have difficulty understanding the void EdgeGyrBias::linearizeOplus() in g2otypes.cc

According to your code: 
```
Sophus::SO3_orb errR ( dRbij.transpose() * Rwbi.transpose() * Rwbj ); // dRij^T * Riw * Rwj
Matrix3d Jlinv = Sophus::SO3_orb::JacobianLInv(errR.log());
_jacobianOplusXi = - Jlinv * J_dR_bg;
```

Can you please elaborate on how you derived this or point to the resource? I couldn't find the corresponding equation in IMU Preintegration paper.

**Comment by jingpang** [comment]
As measurement R12 = Rw1^T * Rw2.
So I defined the error as Rerr = R12^T * (Rw1^T * Rw2), and get its logarithm.
Then you can derive the jacobian according to the update of rotation, and the method is similar to that in Forster's IMU-Preintegration paper.

Because it's in fact a linear estimation, so you can also use SVD to estimate this gyroscope bias as in the [VINS-Mono](https://github.com/hkUST-Aerial-Robotics/VINS-Mono).
